# Taps
tap "homebrew/core"
tap "homebrew/bundle"
tap "homebrew/services"
tap "caskroom/cask"

brew "node"
brew "neovim"
brew "tmux"
brew "bash-completion"
brew "the_silver_searcher"
brew "jq"
brew "editorconfig"

cask "google-chrome"
cask "iterm2"
cask "discretescroll"
cask "karabiner-elements"
cask "slate"
