#!/usr/bin/env bash
# This script is called from bin/dotfiles.
# It installs a list if programs via homebrew

# list of programs to install
toInstall=(
  node
  tmux
  bash-completion
  the_silver_searcher
)

already_installed() {
  if [[ $(brew $2 list) =~ $1 ]] || [[ "$(type -P $1)" ]]; then
    return 0
  else
    return -1
  fi
}

# install everything that is not already installed
for i in ${toInstall[@]} ; do
  if ! already_installed $i; then
    e_msg "Installing $i"
    brew install $i
    if [ ! $? -eq 0 ];then
      e_error "There was a problem installing $i."
    else
      e_success "$i was successfully installed"
    fi
  fi
done

