#!/usr/bin/env bash

e_msg "Menu bar: disable transparency"
# defaults write NSGlobalDomain AppleEnableMenuBarTransparency -bool false
defaults write com.apple.universalaccess reduceTransparency -bool true

e_msg "Menu bar: show remaining battery in percentage "
defaults write com.apple.menuextra.battery ShowPercent -string "YES"
defaults write com.apple.menuextra.battery ShowTime -string "NO"

e_msg "Finder: show all filename extensions"
defaults write NSGlobalDomain AppleShowAllExtensions -bool true

e_msg "System: Disable the “Are you sure you want to open this application?” dialog"
defaults write com.apple.LaunchServices LSQuarantine -bool false

e_msg "System: Enable full keyboard access for all controls"
defaults write NSGlobalDomain AppleKeyboardUIMode -int 3

e_msg "System: Only use UTF-8 in Terminal.app"
defaults write com.apple.terminal StringEncodings -array 4

e_msg "System: Disable the sound effects on boot"
sudo nvram SystemAudioVolume=" "

e_msg "System: Disable “natural” (Lion-style) scrolling"
defaults write NSGlobalDomain com.apple.swipescrolldirection -bool false

e_msg "System: Disable mouse acceleration"
defaults write .GlobalPreferences com.apple.mouse.scaling -1

e_msg "System: Enable touch click on trackpad"
defaults write com.apple.AppleMultitouchTrackpad Clicking -bool true
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true

e_msg "System: Set keyboard repeat speed"
defaults write -g InitialKeyRepeat -int 15
defaults write -g KeyRepeat -int 2

e_msg "System: Disable shake to find cursor"
defaults write .GlobalPreferences CGDisableCursorLocationMagnification -bool true
